#=================================================
# https://github.com/danxiaonuo/openwrtenv-docker
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动编译并上传镜像

# 设置触发条件
on:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      name:
        description: 'build-openwrtenv'
        required: true
        default: '自动编译openwrtenv'

  # 定时触发编译(每天早5点)
  schedule:
     - cron: '0 21 * * *'
  # 点☆Star触发开始编译
  watch:  
     types: [started]
     
 # 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        BASE_IMAGE_TAG: [24.04, 22.04,20.04]
        include:
          - BASE_IMAGE_TAG: 24.04
            DOCKER_TAG: latest,24.04
            DEPENDS_LIST: depends-ubuntu-2404
          - BASE_IMAGE_TAG: 22.04
            DOCKER_TAG: 22.04
            DEPENDS_LIST: depends-ubuntu-2204
          - BASE_IMAGE_TAG: 20.04
            DOCKER_TAG: 20.04
            DEPENDS_LIST: depends-ubuntu-2004
          
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出各个模块代码
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 构建镜像并发布Dockerhub
      uses: docker/build-push-action@v1
      with:
        push: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/openwrtenv
        tags: ${{ matrix.DOCKER_TAG }}
        build_args: BASE_IMAGE_TAG=${{ matrix.BASE_IMAGE_TAG }},DEPENDS_LIST=${{ matrix.DEPENDS_LIST }}
        dockerfile: Dockerfile
        path: .
      
    - name: 上传至阿里云
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hongkong.aliyuncs.com'
        namespaces: 'danxiaonuo'
        repository_name: 'openwrtenv'
        user_name: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        image_version: ${{ matrix.DOCKER_TAG }}
        docker_file: '.'
  
    - name: 删除旧的GitHub-workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1    #保留多少个workflow不删除    
